name: viam_sdk
description: Viam Robotics Flutter SDK. Connect to your Viam robots using WebRTC or gRPC, and control your robots remotely.
version: 0.13.0
homepage: https://github.com/viamrobotics/viam-flutter-sdk/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  grpc: ^4.0.1
  protobuf: ^3.0.0
  image: ^4.0.16
  logger: ^2.0.1
  fixnum: ^1.1.0
  collection: ^1.17.1
  async: ^2.11.0
  bson: ^5.0.5
  uuid: ^4.0.0


dev_dependencies:
  test: ^1.28.0
  mockito: ^5.4.0
  path: ^1.8.2
  build_runner: ^2.3.3
