name: viam_sdk
description: Viam Robotics Flutter SDK. Connect to your Viam robots using WebRTC or gRPC, and control your robots remotely.
version: 0.0.20
homepage: https://github.com/viamrobotics/viam-flutter-sdk/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.10.3
  grpc: ^3.2.3
  protobuf: ^3.0.0
  image: ^4.0.16
  logger: ^2.0.1
  fixnum: ^1.1.0
  flutter_joystick: ^0.0.3
  collection: ^1.17.1
  async: ^2.11.0
  bonsoir: ^5.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  flutter_lints: ^3.0.0
  path: ^1.8.2
  build_runner: ^2.3.3
