name: viam_sdk
description: Viam Robotics Flutter SDK
version: 0.0.1
homepage: https://viam.com

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.9.26
  grpc: ^3.2.3
  protobuf: ^3.0.0
  image: ^4.0.16
  logger: ^1.3.0
  fixnum: ^1.1.0
  flutter_joystick: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  flutter_lints: ^2.0.1
  path: ^1.8.2
  build_runner: ^2.3.3
