name: viam_sdk
description: Viam Robotics Flutter SDK. Connect to your Viam robots using WebRTC or gRPC, and control your robots remotely.
version: 0.11.0
homepage: https://github.com/viamrobotics/viam-flutter-sdk/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.12.1+hotfix.1
  grpc: ^4.0.1
  protobuf: ^3.0.0
  image: ^4.0.16
  logger: ^2.0.1
  fixnum: ^1.1.0
  flutter_joystick: ^0.2.1
  collection: ^1.17.1
  async: ^2.11.0
  bonsoir: ^5.1.8
  bson: ^5.0.5
  uuid: ^4.0.0
  flutter_platform_widgets: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  flutter_lints: ^5.0.0
  path: ^1.8.2
  build_runner: ^2.3.3
